apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: event-monitoring
data:
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_prometheus,rabbitmq_peer_discovery_k8s].
  10-defaults.conf: |
    ## Default configurations
    loopback_users.guest = false
    listeners.tcp.default = 5672
    management.tcp.port = 15672
    prometheus.tcp.port = 15692
    
    ## Memory configuration
    total_memory_available_override_value = 512MB
    
    ## Disk configuration
    disk_free_limit.absolute = 1GB
    
    ## Prometheus metrics
    prometheus.return_per_object_metrics = true