apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: event-monitoring-ingress
  namespace: event-monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /api/events
        pathType: Prefix
        backend:
          service:
            name: event-ingestor-service
            port:
              number: 80
      - path: /events
        pathType: Prefix
        backend:
          service:
            name: event-query-api-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dashboard-service
            port:
              number: 80
